# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 01:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 11, 30, 1, 44, 22, 742927, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='surname',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
